name: Release

on:
  push:
    branches: [ release ]

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: List
        run: |
          ls
      - name: setup node.js
        uses: actions/setup-node@v2.1.2
      - name: Build
        run: |
          cd ui
          npm install 
          npm run-script build
