name: Docker release

on:
  push:
    branches: [ release ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: List
        run: |
          ls
      - name: setup node.js
        uses: actions/setup-node@v2.1.2
      - name: Build UI
        run: |
          cd ui
          npm install 
          npm run-script build
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build app
        run: |
          mkdir src/main/resources/admin/
          cp -r ui/build/* src/main/resources/admin/
          sbt test
  
