name: Docker release

on:
  push:
    branches: [ release ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node.js
        uses: actions/setup-node@v2.1.2
      - name: Build UI
        run: |
          cd ui
          npm install 
          npm run-script build
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build app
        run: |
          mkdir src/main/resources/admin/
          cp -r ui/build/* src/main/resources/admin/
          sbt 'docker:stage'
          sbt 'release with-defaults'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./target/docker/stage/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: pegerto/kinestesia:latest
